### ISSUE TITLE
Import existing image

### ISSUE THREAD

**Issue by alensiljak** [choelzl/keepass-fidelity#1]
Hi! Thanks a lot for this handy plugin!
I am wondering if it would be possible to import an existing code image.
I have an image downloaded from a Web site. Currently I had to scan it from the display of another device but ultimately it would be great if I could simply select an image file for a new entry.

The orientation for the qr codes is built in, while for Barcodes a reasonable expectation would be to use landscape.

**Comment by choelzl** [comment]
Thanks for the feedback,
I will look into adding a button to load from library on the scanner view (not sure about permissions and desirability yet).  

When you click the barcode it sets the brightness to maximum and makes it full screen (by rotating it) , Maybe there is a way to make this more intuitive :)

**Comment by alensiljak** [comment]
Sorry if my remark about the orientation was a bit misleading. I meant in the context of importing an image. I'm typing on the phone so I'm a bit short on words. What I meant is that it is easy to read a QR code from an image but a Barcode is a bit more tricky as it may not be clear from the image file, what the orientation is.

**Comment by alensiljak** [comment]
And thank you for that tip about the full screen Barcode. I don't think I would try that myself, otherwise.
Having a label "tap for full screen", or something like that would indeed be useful.

**Comment by choelzl** [comment]
Should be resolved in new release, added a button to pick an image from library. FYI, barcodes have a internal indicator allowing the scanner to know if they are upside down.
